kakao:
  login-url: ${KAKAO_LOGIN_URL}
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-request-uri: ${KAKAO_TOKEN_REQUEST_URI}
  user-info-request-uri: ${KAKAO_USER_INFO_REQUEST_URI}
